### ISSUE TITLE
form page

### ISSUE THREAD

**Issue by Siddhansthrestha** [neupSudip/E_Challan_Project#1]
1. I think there should be background image for form.
2. E from E- Chalan logo should be white like in the screenshot i have sent you

![Screenshot 2021-04-14 134541](https://user-images.githubusercontent.com/81379854/114675938-83c65d00-9d28-11eb-8455-9eb350236c35.png)

**Comment by neupSudip** [comment]
I have changed as per the requirement. Please Review it
