### ISSUE TITLE
unresponsive pages

### ISSUE THREAD

**Issue by shresthasafal** [neupSudip/E_Challan_Project#2]
![login-signup](https://user-images.githubusercontent.com/81407211/116818055-1ff5be00-ab89-11eb-960e-2dd739eec888.png)
![form](https://user-images.githubusercontent.com/81407211/116818058-21bf8180-ab89-11eb-8ab7-bfe58df821d6.png)

**Comment by neupSudip** [comment]
responsive has been added in all pages
