### ISSUE TITLE
The help Page doesn't have any page linked to it. It just shows us the previous page that we have been to 

### ISSUE THREAD

**Issue by shresthasafal** [neupSudip/E_Challan_Project#6]
![Screenshot (198)](https://user-images.githubusercontent.com/81407211/118347274-a1722680-b561-11eb-8284-46f68b927a25.png)

**Comment by neupSudip** [comment]
We have no more such according to product backlog. But i asked PM about it and he said "There needs no content but make sure it looks ok". So i added it just to look good. If you want me to remove it, I will just do that.

**Comment by Siddhansthrestha** [comment]
I have removed the help page as we discussed in the group meeting
